version: "3"
services:
  mongo: 
    image: "mongo:7.0"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
      - ./mongodb/log:/var/log/mongodb
    command: ["mongod", "--logpath", "/var/log/mongodb/mongo.log", "--logappend"]
    networks:
      - backend

  nginx:
    build:
      context: ./Nginx
    ports:
      - 8198:8198
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NGINX_PORT=8198
    networks:
      - backend
    depends_on:
      - service1
      - service2

  service1:
    build:
      context: ./Service1
      dockerfile: Dockerfile.prod
    environment:
      - SLEEPSECONDS=2
      - PORT=8199
    deploy:
      replicas: 3
    networks:
      - backend

  service2:
    build:
      context: ./Service2
      dockerfile: Dockerfile.prod
    environment:
      - PORT=5000
    networks:
      - backend
    depends_on:
      - service1  

  gateway:
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile.prod
    environment:
      - PORT=8197
      - RUN_TESTS=NO
    ports:
      - "8197:8197"
    networks:
      - backend
    depends_on:
      - service1
      - service2

  stateservice:
    build:
      context: .
      dockerfile: ./StateService/Dockerfile.prod
    environment:
      - PORT=8195
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_IP=${MONGO_IP}
      - MONGO_DB=${MONGO_DB}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
    # ports:
    #   - "8195:8195"
    networks:
      - backend
    depends_on:
      - mongo
      - service1
      - service2
  
networks:
  backend:

volumes:
  mongodb:
