version: "3"
services:
  nginx:
    build:
      context: ./Nginx
    ports:
      - 8198:8198
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NGINX_PORT=8198
    networks:
      - backend
    depends_on:
      - service1
      - service2

  service1:
    build:
      context: ./Service1
      dockerfile: Dockerfile.prod
    environment:
      - SLEEPSECONDS=2
      - PORT=8199
    deploy:
      replicas: 3
    networks:
      - backend

  service2:
    build:
      context: ./Service2
      dockerfile: Dockerfile.prod
    environment:
      - PORT=5000
    networks:
      - backend
    depends_on:
      - service1  

  gateway:
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile.prod
    environment:
      - PORT=8197
      - RUN_TESTS=NO
    ports:
      - "8197:8197"
    networks:
      - backend
    depends_on:
      - service1
      - service2

networks:
  backend: