FROM node:21-slim

WORKDIR ./app

COPY ./Service1/. ./app/
COPY ./tests/service1_tests/ /app/test/
COPY ./Service1/package.json ./package.json



ARG NODE_ENV
RUN npm install;

CMD ["npm", "run", "test"]


