FROM python:3.9-slim

WORKDIR /app
COPY . /app
# COPY ./tests/service2_tests/test_app.py /app/

COPY ./tests/service2_tests /app/tests/service2_tests

RUN pip install flask psutil pytest pytest-flask

# CMD ["pytest"]

ENV PYTHONPATH=/app
CMD ["pytest", "/app/tests/service2_tests"]

