FROM python:3.9-slim

WORKDIR /app
COPY . /app
COPY ./tests/service2_tests/ /app/test/

RUN ls -R /app
RUN pip install flask psutil pytest pytest-flask

# CMD ["pytest"]

ENV PYTHONPATH=/app
CMD ["pytest", "/app/Service2/"]
# CMD ["pytest", "/app/tests/service2_tests"]
# CMD ["sh", "-c", "ls -R /app/tests && pytest /app/tests/service2_tests"]

